=== amri-amri/procake-extension/src/main/resources/de/uni_trier/wi2/dtd/methodinvokers-function.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT method-invokers-function (if)* >

<!ELEMENT if ((and | or | not | equals | same-object-as | instance-of | regex | function), method-list) >

<!ELEMENT and ((and | or | not | equals | same-object-as | instance-of | regex | function), (and | or | not | equals | same-object-as | instance-of | regex | function), (and | or | not | equals | same-object-as | instance-of | regex | function)*) >
<!ELEMENT or ((and | or | not | equals | same-object-as | instance-of | regex | function), (and | or | not | equals | same-object-as | instance-of | regex | function), (and | or | not | equals | same-object-as | instance-of | regex | function)*) >
<!ELEMENT not ((and | or | not | equals | same-object-as | instance-of | regex | function)) >

<!ELEMENT equals ((q | c | string | double | boolean | method-return-value),(q | c | string | double | boolean | method-return-value)) >
<!ELEMENT same-object-as ((q | c | string | double | boolean | method-return-value),(q | c | string | double | boolean | method-return-value)) >

<!ELEMENT instance-of ((q | c | method-return-value),(string)) >

<!ELEMENT regex ((string | method-return-value), (string | method-return-value)) >

<!ELEMENT q EMPTY >
<!ELEMENT c EMPTY >

<!ELEMENT string EMPTY >
<!ATTLIST string value CDATA #REQUIRED >

<!ELEMENT double EMPTY >
<!ATTLIST double value CDATA #REQUIRED >

<!ELEMENT boolean EMPTY >
<!ATTLIST boolean value CDATA #REQUIRED >

<!ELEMENT character EMPTY >
<!ATTLIST character value CDATA #REQUIRED >

<!ELEMENT integer EMPTY >
<!ATTLIST integer value CDATA #REQUIRED >

<!ELEMENT method-return-value ((q | c | method-return-value), method) >

<!ELEMENT method (string | double | boolean | character | integer)* >
<!ATTLIST method name CDATA #REQUIRED >

<!ELEMENT method-list (method)* >

<!ELEMENT function EMPTY >
<!ATTLIST function name (qcAttributesHaveSameKeyAndType | qAttributeHasKeyTypeValue | qEventContainsAttribute | cAttributeHasKeyTypeValue | cEventContainsAttribute) #REQUIRED
    arg1 CDATA #IMPLIED
    arg2 CDATA #IMPLIED
    arg3 CDATA #IMPLIED >

=== amri-amri/procake-extension/src/test/resources/de/uni_trier/wi2/parallel/mif.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE method-invokers-function SYSTEM
        "https://karim-amri.de/dtd/methodinvokers-function.dtd">
<method-invokers-function>
    <if>
        <and>
            <equals>
                <method-return-value>
                    <method-return-value>
                        <q/>
                        <method name="getDataClass"/>
                    </method-return-value>
                    <method name="getName"/>
                </method-return-value>
                <method-return-value>
                    <method-return-value>
                        <c/>
                        <method name="getDataClass"/>
                    </method-return-value>
                    <method name="getName"/>
                </method-return-value>
            </equals>
            <equals>
                <method-return-value>
                    <method-return-value>
                        <q/>
                        <method name="getDataClass"></method>
                    </method-return-value>
                    <method name="getName"/>
                </method-return-value>
                <string value="XESStringClass"/>
            </equals>
        </and>
        <method-list>
            <method name="setCaseInsensitive"/>
        </method-list>
    </if>
</method-invokers-function>
